"use client";
import { useEffect, useMemo, useState } from "react";
export default function AdminWithdrawalsPage(){
 const [items,setItems]=useState<any[]>([]),[tab,setTab]=useState("PENDING"),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/withdrawals",{credentials:"include",cache:"no-store"});const d=await r.json();if(r.ok)setItems(d.withdrawals||[]);else alert(d.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function action(id:string,kind:"approve"|"reject"|"paid"){let remarks="",payoutTxHash="";if(kind==="reject")remarks=prompt("Reason (optional):")||"";if(kind==="paid")payoutTxHash=prompt("External payout transaction hash/reference:")||"";if(kind==="paid"&&!payoutTxHash)return;const r=await fetch(`/api/admin/withdrawals/${id}/${kind}`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({remarks,payoutTxHash})});const d=await r.json();alert(d.message);if(r.ok)load()}
 const filtered=useMemo(()=>tab==="ALL"?items:items.filter(x=>x.status===tab),[items,tab]);
 return <main className="min-h-screen bg-[#050816] text-white p-6 md:p-8"><div className="max-w-7xl mx-auto"><div className="mb-8"><p className="text-cyan-300 tracking-[.25em] text-xs">STRIVERSE ADMIN</p><h1 className="text-4xl font-bold mt-2">Referral Withdrawals</h1><p className="text-gray-400 mt-2">Review, approve and record external USDT payouts.</p></div><div className="flex gap-2 flex-wrap mb-6">{["PENDING","APPROVED","PAID","REJECTED","ALL"].map(x=><button key={x} onClick={()=>setTab(x)} className={`px-4 py-2 rounded-xl ${tab===x?"bg-cyan-500 text-black":"bg-white/10"}`}>{x} ({x==="ALL"?items.length:items.filter(i=>i.status===x).length})</button>)}</div><div className="overflow-x-auto rounded-2xl border border-cyan-500/20 bg-white/5"><table className="w-full"><thead className="bg-white/10"><tr>{["User","Amount","Network","Wallet","Status","Date","Actions"].map(h=><th key={h} className="p-4 text-left">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-10 text-center text-gray-400">Loading...</td></tr>:filtered.map(x=><tr key={x.id} className="border-t border-white/10"><td className="p-4"><b>{x.user.fullName}</b><div className="text-xs text-gray-400">{x.user.email}</div></td><td className="p-4">{Number(x.amount).toFixed(2)} USDT</td><td className="p-4">{x.network}</td><td className="p-4 max-w-[240px] truncate">{x.walletAddress}</td><td className="p-4"><span className="px-3 py-1 rounded-full text-xs bg-white/10">{x.status}</span></td><td className="p-4">{new Date(x.createdAt).toLocaleString()}</td><td className="p-4"><div className="flex gap-2">{x.status==="PENDING"&&<><button onClick={()=>action(x.id,"approve")} className="px-3 py-2 rounded-lg bg-green-500 text-black">Approve</button><button onClick={()=>action(x.id,"reject")} className="px-3 py-2 rounded-lg bg-red-500">Reject</button></>}{x.status==="APPROVED"&&<button onClick={()=>action(x.id,"paid")} className="px-3 py-2 rounded-lg bg-blue-500 text-black">Mark Paid</button>}</div></td></tr>)}</tbody></table></div><p className="text-xs text-gray-500 mt-5">Mark Paid only after the external USDT transfer has actually been completed and its transaction reference has been recorded.</p></div></main>
}
