import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import bcrypt from "bcryptjs";
import { requireDeveloper } from "@/lib/adminGuard";
export async function GET(){const d=await requireDeveloper();if(!d)return NextResponse.json({success:false,message:"Developer access required."},{status:403});const admins=await prisma.user.findMany({where:{role:{in:["ADMIN","DEVELOPER"]}},select:{id:true,fullName:true,email:true,phone:true,role:true,isVerified:true,isBlocked:true,adminPermissions:true},orderBy:{role:"desc"}});return NextResponse.json({success:true,admins});}
export async function POST(req:NextRequest){const d=await requireDeveloper(req);if(!d)return NextResponse.json({success:false,message:"Developer access required."},{status:403});const count=await prisma.user.count({where:{role:"ADMIN"}});if(count>=3)return NextResponse.json({success:false,message:"Exactly three Admin seats are allowed."},{status:400});const b=await req.json();if(!b.fullName||!b.email||!b.password)return NextResponse.json({success:false,message:"Name, email and password are required."},{status:400});const exists=await prisma.user.findUnique({where:{email:String(b.email).toLowerCase()}});if(exists)return NextResponse.json({success:false,message:"Email already exists."},{status:409});const hashed=await bcrypt.hash(String(b.password),10);const admin=await prisma.user.create({data:{fullName:String(b.fullName),email:String(b.email).toLowerCase(),phone:String(b.phone||"0000000000"),password:hashed,role:"ADMIN",isVerified:true,referralCode:`ADMIN${Date.now().toString().slice(-8)}`}});
const modules=Array.isArray(b.permissions)?b.permissions:[]; if(modules.length) await prisma.adminPermission.createMany({data:modules.map((module:string)=>({adminId:admin.id,module,action:"VIEW",scope:"ASSIGNED",enabled:true})),skipDuplicates:true});await prisma.securityAuditLog.create({data:{userId:d.id,actorRole:d.role,action:"ADMIN_CREATED",metadata:JSON.stringify({adminId:admin.id,email:admin.email})}});return NextResponse.json({success:true,admin:{id:admin.id,fullName:admin.fullName,email:admin.email,role:admin.role}});}
export async function PATCH(req:NextRequest){const d=await requireDeveloper(req);if(!d)return NextResponse.json({success:false,message:"Developer access required."},{status:403});const b=await req.json();if(!b.id||!Array.isArray(b.permissions))return NextResponse.json({success:false,message:"Admin id and permissions are required."},{status:400});const target=await prisma.user.findUnique({where:{id:b.id}});if(!target||target.role!=="ADMIN")return NextResponse.json({success:false,message:"Admin not found."},{status:404});const modules=[...new Set(b.permissions as string[])];await prisma.$transaction(async tx=>{await tx.adminPermission.deleteMany({where:{adminId:b.id}});if(modules.length)await tx.adminPermission.createMany({data:modules.map(module=>({adminId:b.id,module,action:"VIEW",scope:"ASSIGNED",enabled:true}))});await tx.securityAuditLog.create({data:{userId:d.id,actorRole:d.role,action:"ADMIN_PERMISSIONS_UPDATED",metadata:JSON.stringify({adminId:b.id,modules})}})});return NextResponse.json({success:true,message:"Admin permissions updated."});}
export async function DELETE(req:NextRequest){const d=await requireDeveloper(req);if(!d)return NextResponse.json({success:false,message:"Developer access required."},{status:403});const {id}=await req.json();if(!id||id===d.id)return NextResponse.json({success:false,message:"Cannot delete Developer."},{status:400});const target=await prisma.user.findUnique({where:{id}});if(!target||target.role!=="ADMIN")return NextResponse.json({success:false,message:"Admin not found."},{status:404});await prisma.user.update({where:{id},data:{role:"USER",isVerified:false}});await prisma.securityAuditLog.create({data:{userId:d.id,actorRole:d.role,action:"ADMIN_REMOVED",metadata:JSON.stringify({adminId:id})}});return NextResponse.json({success:true,message:"Admin removed."});}
