"use client";
import { useEffect, useMemo, useState } from "react";
import { Gift, RefreshCw, Search, Copy, Users, DollarSign } from "lucide-react";
import type { LucideIcon } from "lucide-react";

type Row = { id:string; fullName:string; email:string; referralCode:string; totalReferrals:number; referralEarnings:number; referredBy?:{fullName:string; referralCode:string}|null; bonusWallet?:{referralPending:number; referralAvailable:number; referralWithdrawn:number}|null };
export default function ReferralsPage(){
 const [rows,setRows]=useState<Row[]>([]); const [q,setQ]=useState(""); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true); try{const r=await fetch('/api/admin/referrals',{credentials:'include',cache:'no-store'}); const d=await r.json(); if(r.ok)setRows(d.users||[]);}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const x=q.toLowerCase().trim(); return !x?rows:rows.filter(u=>[u.fullName,u.email,u.referralCode,u.referredBy?.fullName,u.referredBy?.referralCode].some(v=>v?.toLowerCase().includes(x)))},[rows,q]);
 const total=rows.reduce((n,u)=>n+u.totalReferrals,0), pending=rows.reduce((n,u)=>n+(u.bonusWallet?.referralPending||0),0), available=rows.reduce((n,u)=>n+(u.bonusWallet?.referralAvailable||0),0);
 const cards: Array<{Icon: LucideIcon; val: number; label: string}> = [{Icon: Users, val: total, label: 'Total referrals'}, {Icon: DollarSign, val: pending, label: 'Pending USDT'}, {Icon: Gift, val: available, label: 'Available USDT'}];
 return <main className="min-h-full text-white"><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm uppercase tracking-[.25em] text-cyan-300/70">Partner center</p><h1 className="mt-2 text-3xl font-bold">Partner Program</h1><p className="mt-1 text-sm text-slate-400">Track partner relationships and USDT bonus balances.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm hover:bg-white/10"><RefreshCw size={16}/> Refresh</button></div>
 <div className="mb-6 grid gap-4 sm:grid-cols-3">{cards.map(({Icon,val,label})=>{const I=Icon; return <div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.04] p-5 backdrop-blur-xl"><div className="flex items-center justify-between text-sm text-slate-400">{label}<I size={18} className="text-cyan-300"/></div><div className="mt-2 text-2xl font-bold">{typeof val==='number'&&String(label).includes('USDT')?`$${val.toFixed(2)}`:val}</div></div>})}</div>
 <div className="rounded-3xl border border-white/10 bg-white/[.04] backdrop-blur-xl"><div className="border-b border-white/10 p-5"><div className="relative max-w-md"><Search size={17} className="absolute left-3 top-3 text-slate-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search user or partner code" className="w-full rounded-xl border border-white/10 bg-black/20 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-cyan-400/50"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-black/20 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">User</th><th className="px-5 py-4">Partner Code</th><th className="px-5 py-4">Referred By</th><th className="px-5 py-4">Referrals</th><th className="px-5 py-4">Pending</th><th className="px-5 py-4">Available</th><th className="px-5 py-4">Withdrawn</th></tr></thead><tbody className="divide-y divide-white/5">{loading?<tr><td colSpan={7} className="px-5 py-12 text-center text-slate-500">Loading referrals…</td></tr>:filtered.map(u=><tr key={u.id} className="hover:bg-white/[.025]"><td className="px-5 py-4"><div className="font-semibold">{u.fullName}</div><div className="text-xs text-slate-500">{u.email}</div></td><td className="px-5 py-4"><button onClick={()=>navigator.clipboard?.writeText(u.referralCode)} className="inline-flex items-center gap-1 rounded-lg bg-white/5 px-2.5 py-1.5 font-mono text-xs text-cyan-300">{u.referralCode}<Copy size={12}/></button></td><td className="px-5 py-4">{u.referredBy?<><div>{u.referredBy.fullName}</div><div className="text-xs text-slate-500">{u.referredBy.referralCode}</div></>:<span className="text-slate-600">Direct</span>}</td><td className="px-5 py-4 font-semibold">{u.totalReferrals}</td><td className="px-5 py-4 text-amber-300">${(u.bonusWallet?.referralPending||0).toFixed(2)}</td><td className="px-5 py-4 text-emerald-300">${(u.bonusWallet?.referralAvailable||0).toFixed(2)}</td><td className="px-5 py-4 text-slate-300">${(u.bonusWallet?.referralWithdrawn||0).toFixed(2)}</td></tr>)}</tbody></table></div></div></main>
}
