ALTER TABLE "User" ADD COLUMN "recoveryUsed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "recoveryRequestedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN "recoveryResetAt" TIMESTAMP(3);

ALTER TABLE "Purchase" ADD COLUMN "packageName" TEXT NOT NULL DEFAULT 'LUNA';
ALTER TABLE "Purchase" ADD COLUMN "referralBonusUSDT" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN "referralUnlockAt" TIMESTAMP(3);
ALTER TABLE "Purchase" ADD COLUMN "referralBonusReleased" BOOLEAN NOT NULL DEFAULT false;
